### ISSUE TITLE
Failed to parse Google Chrome AXML

### ISSUE THREAD

**Issue by ghost** [Ayrx/axmldecoder#2]
File: https://apkpure.com/google-chrome-fast-secure/com.android.chrome/variant/103.0.5060.129-APK

error:
```
Namespace missing: http://schemas.android.com/apk/res/android',
```

**Comment by Ayrx** [comment]
Fixed in a40580820b61396580deed67d86371224f846922. This is a very weird sample where there is no `RES_XML_START_NAMESPACE_TYPE` chunk, never came across that before.

Keep the issues coming if you see anything else! I'll cut a new release with the updates in a few days if I haven't heard anything else from you. :)

**Comment by ghost** [comment]
I'm downloading 200gb of APK files and will scan for all of them but need to wait until the weekends to test properly

**Comment by Ayrx** [comment]
@grubeli You have code to pull the APKs from the Play Store or somewhere else? Is that public anywhere or could you share it? I've been meaning to write something for that since all the ones I've seen are pretty dodgy.

**Comment by ghost** [comment]
will try to use this one: https://archive.org/details/2018-02-random-apk-collection

**Comment by ghost** [comment]
this collection also looks solid: https://archive.org/details/phonesoftware
